FROM node:22-alpine
WORKDIR /app

RUN npm install -g pnpm

# Solo copiamos los archivos de configuración primero para aprovechar la caché
COPY package.json pnpm-lock.yaml tsconfig*.json vite.config.* tailwind.config.js postcss.config.js ./
RUN pnpm install

# No copiamos el código fuente, lo montaremos como volumen

EXPOSE 3000

# Comando para iniciar el servidor de desarrollo
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"] 