name: Deploy to Digital Ocean Droplet

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no agile-system@161.35.97.194 "
            cd /home/agile-system/app && 
            git pull origin ${{ github.ref_name }} && 
            cd infra/podman && 
            ./start-environment.sh --no-pgadmin --build
          " 